name: Sincronizar y Limpiar Fork

on:
  schedule:
    # Se ejecuta a las 00:00 y 12:00 UTC
    - cron: '0 0,12 * * *'
  workflow_dispatch:

jobs:
  sync-fork:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out hijo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configurar Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@://github.com"

      - name: Agregar repositorio padre (Upstream)
        run: |
          # URL por la del repositorio original (padre)
          git remote add upstream https://github.com/keiyoushi/extensions-source
          git fetch upstream main

      - name: Verificar si hay actualizaciones
        id: check_changes
        run: |
          LOCAL=$(git rev-parse HEAD)
          UPSTREAM=$(git rev-parse upstream/main)
          if [ "$LOCAL" = "$UPSTREAM" ]; then
            echo "No hay actualizaciones en el repositorio padre. Terminando correctamente."
            echo "has_updates=false" >> $GITHUB_OUTPUT
          else
            echo "Se encontraron nuevas actualizaciones."
            echo "has_updates=true" >> $GITHUB_OUTPUT
          fi

      - name: Aplicar cambios y limpiar
        # Solo se ejecuta si el paso anterior confirmó que hay actualizaciones
        if: steps.check_changes.outputs.has_updates == 'true'
        run: |
          git checkout main
          git merge upstream/main --no-commit --no-ff || true

          echo "Eliminando carpetas de idiomas no deseados en src..."
          for dir in src/*/; do
            if [ -d "$dir" ]; then
              folder_name=$(basename "$dir")
              if [ "$folder_name" != "en" ] && [ "$folder_name" != "all" ] && [ "$folder_name" != "es" ]; then
                echo "Borrando: src/$folder_name"
                rm -rf "$dir"
              fi
            fi
          done

          # Verifica si después de borrar las carpetas realmente hay cambios para commitear
          if git diff --quiet && git diff --staged --quiet; then
            echo "El repositorio ya estaba al día tras filtrar los idiomas. No se requiere commit."
          else
            git add .
            git commit -m "sync: actualizaciones del padre (solo en, all, es)"
            git push origin main
          fi
